schema = 3

[mod]
  [mod."dario.cat/mergo"]
    version = "v1.0.1"
    hash = "sha256-wcG6+x0k6KzOSlaPA+1RFxa06/RIAePJTAjjuhLbImw="
  [mod."filippo.io/edwards25519"]
    version = "v1.1.0"
    hash = "sha256-9ACANrgWZSd5HYPfDZHY8DVbPSC9LOMgy8deq3rDOoc="
  [mod."github.com/AndreasBriese/bbloom"]
    version = "v0.0.0-20190825152654-46b345b51c96"
    hash = "sha256-ydIJ4QKvQsDSAook9y0doDaTeXpyQUy1T+ySfOgFLAg="
  [mod."github.com/Azure/go-ntlmssp"]
    version = "v0.0.0-20221128193559-754e69321358"
    hash = "sha256-tkVqtJKQZl5WUJSe9FZBCPwuD//WPleYvrQ46rkD4jU="
  [mod."github.com/Masterminds/goutils"]
    version = "v1.1.1"
    hash = "sha256-MEvA5e099GUllILa5EXxa6toQexU1sz6eDZt2tiqpCY="
  [mod."github.com/Masterminds/semver/v3"]
    version = "v3.3.0"
    hash = "sha256-fBG3nuxEW+0fRHegSzj7q4GyEMCINeOUbkfqFG2cU+8="
  [mod."github.com/Masterminds/sprig/v3"]
    version = "v3.3.0"
    hash = "sha256-NvFX1xRO5t/u8OI063SDPfqYcZ43AuLI6klA6daPV9I="
  [mod."github.com/Microsoft/go-winio"]
    version = "v0.6.2"
    hash = "sha256-tVNWDUMILZbJvarcl/E7tpSnkn7urqgSHa2Eaka5vSU="
  [mod."github.com/abiosoft/caddy-json-schema"]
    version = "v0.0.0-20220621031927-c4d6e132f3af"
    hash = "sha256-HdSRugUWQPQ6BAv1Qt0PP09yke8qHnvKZY+J27ofOos="
  [mod."github.com/antlr4-go/antlr/v4"]
    version = "v4.13.1"
    hash = "sha256-beAuxHNRUuhzcSJUh/8ztVf1zCUiaT72fg2Jvx0AuNQ="
  [mod."github.com/aryann/difflib"]
    version = "v0.0.0-20210328193216-ff5ff6dc229b"
    hash = "sha256-QaGcdek1bA6eekbxVTDaidFZrWeGk+of35NTV94lVXw="
  [mod."github.com/beevik/etree"]
    version = "v1.4.1"
    hash = "sha256-R6ck41gi8GmzNY4isP6X6GcgkVB5XSXfgFvtwzmE2yk="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/caddy-dns/cloudflare"]
    version = "v0.0.0-20240703190432-89f16b99c18e"
    hash = "sha256-XTNt2QfbKmt+Dryce8FRVhLrHdPkxhj0PPjCDijMuEs="
  [mod."github.com/caddyserver/caddy/v2"]
    version = "v2.8.4"
    hash = "sha256-Cwnn4zudKQApxVxmdIFSiD813S00qzdmFjAA1PFoTE8="
  [mod."github.com/caddyserver/certmagic"]
    version = "v0.21.3"
    hash = "sha256-UhKUVN3a1iAcGk2KtLKD9PBf6rtmIFb8jVVuCdKBHuc="
  [mod."github.com/caddyserver/replace-response"]
    version = "v0.0.0-20240710174758-f92bc7d0c29d"
    hash = "sha256-EZ9l4XdF3C9+cpsoDpznct1wT3VsV8LHzgo9kGm+1v8="
  [mod."github.com/caddyserver/zerossl"]
    version = "v0.1.3"
    hash = "sha256-BqaTshe3Hum7YSILJNFG0Y2fzgwFN42FzU2qQXWluZo="
  [mod."github.com/cespare/xxhash"]
    version = "v1.1.0"
    hash = "sha256-nVDTtXH9PC3yJ0THaQZEN243UP9xgLi/clt5xRqj3+M="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/chzyer/readline"]
    version = "v1.5.1"
    hash = "sha256-6wKd6/JZ9/O7FwSyNKE3KOt8fVPZEunqbTHQUxlOUNc="
  [mod."github.com/coreos/go-oidc/v3"]
    version = "v3.11.0"
    hash = "sha256-iV7ff6YGPiorHFPxC6lnojYWszFjkgh86445eUvYywI="
  [mod."github.com/cpuguy83/go-md2man/v2"]
    version = "v2.0.4"
    hash = "sha256-pQ+H8Psh92KWTang8hK0cHFLomH+4X0rMMilIJUQ4Qc="
  [mod."github.com/crewjam/httperr"]
    version = "v0.2.0"
    hash = "sha256-bDtSUX19gEMm/U92fLAiNZSKWmco9rvl6u8avD5oTyo="
  [mod."github.com/crewjam/saml"]
    version = "v0.4.14"
    hash = "sha256-84AX5JZfYAc8Lc1KriakVliW0tPY3GeEbucIK/PTbN8="
  [mod."github.com/dgraph-io/badger"]
    version = "v1.6.2"
    hash = "sha256-D/iXyiNZ8/7tBtA9msk10vVWfohWEPqFdobzRwKlvQQ="
  [mod."github.com/dgraph-io/badger/v2"]
    version = "v2.2007.4"
    hash = "sha256-+KwqZJZpViv8S3TqUVvPXrFoMgWFyS3NoLsi4RR5fGk="
  [mod."github.com/dgraph-io/ristretto"]
    version = "v0.1.1"
    hash = "sha256-Wr9ovXhGi71+n37EnrpIj2o9goyaQHtY4Vvurv6IVlY="
  [mod."github.com/dgryski/go-farm"]
    version = "v0.0.0-20200201041132-a6ae2369ad13"
    hash = "sha256-aOMlPwFY36bLiiIx4HonbCYRAhagk5N6HAWN7Ygif+E="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/emersion/go-sasl"]
    version = "v0.0.0-20231106173351-e73c9f7bad43"
    hash = "sha256-u1t+T7AKWEtzHynyrfmGu9/410MA5smqC73GVdGtZL8="
  [mod."github.com/emersion/go-smtp"]
    version = "v0.21.3"
    hash = "sha256-hh0KOKzK+7O/GxKsLOKm3DsjWD+b2hlF8pK4Oqe2O/0="
  [mod."github.com/go-asn1-ber/asn1-ber"]
    version = "v1.5.7"
    hash = "sha256-omBQHBj3XvqYDc8TM59RK2H3EdaJ5X0FyC7pKHDQQXU="
  [mod."github.com/go-ini/ini"]
    version = "v1.67.0"
    hash = "sha256-V10ahGNGT+NLRdKUyRg1dos5RxLBXBk1xutcnquc/+4="
  [mod."github.com/go-jose/go-jose/v3"]
    version = "v3.0.3"
    hash = "sha256-PsjN1vVhAFI6X11iIkpQU4i7Ax6FvkhXNxApeBa2BvA="
  [mod."github.com/go-jose/go-jose/v4"]
    version = "v4.0.4"
    hash = "sha256-847SAFF8Zo3QN0sl3G3MMARQKZxjotgJF2+5Fm7RFQ4="
  [mod."github.com/go-kit/kit"]
    version = "v0.13.0"
    hash = "sha256-EncDzq0JVtY+NLlW5lD+nbVewNYTTrfzlOxI4PuwREw="
  [mod."github.com/go-kit/log"]
    version = "v0.2.1"
    hash = "sha256-puLJ+up45X2j9E3lXvBPKqHPKOA/sFAhfCqGxsITW/Y="
  [mod."github.com/go-ldap/ldap/v3"]
    version = "v3.4.8"
    hash = "sha256-KOtyqx7LnmSugBgwxBrurP1iBheNdrFOphHggcc7g5g="
  [mod."github.com/go-logfmt/logfmt"]
    version = "v0.6.0"
    hash = "sha256-RtIG2qARd5sT10WQ7F3LR8YJhS8exs+KiuUiVf75bWg="
  [mod."github.com/go-sql-driver/mysql"]
    version = "v1.8.1"
    hash = "sha256-Vp/au38P1tf1jNTBW34rdb5mly0cde5IIXu+EMjDDUY="
  [mod."github.com/go-task/slim-sprig/v3"]
    version = "v3.0.0"
    hash = "sha256-vCCw4MXVBm33VNLXcOBccVDD1CSnzDvDdWB6w5FN1cA="
  [mod."github.com/goccy/go-json"]
    version = "v0.10.3"
    hash = "sha256-ZOzfwCXh+qp+hp+UnC0t422hUV0Cq5KANXkx8hcLp7s="
  [mod."github.com/golang-jwt/jwt/v4"]
    version = "v4.5.0"
    hash = "sha256-dyKL8wQRApkdCkKxJ1knllvixsrBLw+BtRS0SjlN7NQ="
  [mod."github.com/golang/glog"]
    version = "v1.2.2"
    hash = "sha256-AIPEkLcrbIw49fuTDKfDifVLCtSpFPHgujQ/c99dPqk="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.4"
    hash = "sha256-N3+Lv9lEZjrdOWdQhFj6Y3Iap4rVLEQeI8/eFFyAMZ0="
  [mod."github.com/golang/snappy"]
    version = "v0.0.4"
    hash = "sha256-Umx+5xHAQCN/Gi4HbtMhnDCSPFAXSsjVbXd8n5LhjAA="
  [mod."github.com/google/cel-go"]
    version = "v0.21.0"
    hash = "sha256-DFRBwrD8BhKQq7z+48KwXWoXtKB0EQWSDkrDyog14XY="
  [mod."github.com/google/pprof"]
    version = "v0.0.0-20240910150728-a0b0bb1d4134"
    hash = "sha256-lOzZBFXv2oaOT4+mLGqPzzvp12jj+ok52dXSmP1nipU="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.1"
    hash = "sha256-eHZ/U+eeE5tSgWc1jEDuBwtTRbXKP9fqP9zfW4Zw8T0="
  [mod."github.com/greenpau/caddy-security"]
    version = "v1.1.29"
    hash = "sha256-UTwaptCJGGQYuZpYQ1Bl86kOlPNd9m2uD4WXvk03W38="
  [mod."github.com/greenpau/go-authcrunch"]
    version = "v1.1.4"
    hash = "sha256-rcVfbM0BSjgBOyEtBKFCb0sHzbCTYEePXbqPA7dBRac="
  [mod."github.com/greenpau/versioned"]
    version = "v1.0.30"
    hash = "sha256-YJPYBdj2BGMrOJ/A2Jbqrk7/OTyzfa+oU0YBj8oUrTU="
  [mod."github.com/huandu/xstrings"]
    version = "v1.5.0"
    hash = "sha256-q4F/rzbWMDmOVv07RVApdpfIsRNRByfOUQPEKsTq5BM="
  [mod."github.com/icholy/replace"]
    version = "v0.6.0"
    hash = "sha256-tXSquEOLmfv62h1jFefqBzu7m408l2ECyNg9f5Yo3CE="
  [mod."github.com/imgk/caddy-trojan"]
    version = "v0.0.0-20240603105249-3fcb4dacf8f0"
    hash = "sha256-W8GMHMP6uh0jCwfAMtQncb6zwdyw3La7jreMgvTgq8o="
  [mod."github.com/imgk/memory-go"]
    version = "v0.0.0-20220328012817-37cdd311f1a3"
    hash = "sha256-mLr09Z492OliFegOEOD7OZILUxzIbzct5CX9xTB6C7c="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/jackc/pgpassfile"]
    version = "v1.0.0"
    hash = "sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM="
  [mod."github.com/jackc/pgservicefile"]
    version = "v0.0.0-20240606120523-5a60cdf6a761"
    hash = "sha256-ETpGsLAA2wcm5xJBayr/mZrCE1YsWbnkbSSX3ptrFn0="
  [mod."github.com/jackc/pgx/v5"]
    version = "v5.7.1"
    hash = "sha256-N0aiHG91gMztyWC3PAEG0JVd6B/yrcOCfdl0NzqCDXk="
  [mod."github.com/jackc/puddle/v2"]
    version = "v2.2.2"
    hash = "sha256-IUxdu4JYfsCh/qlz2SiUWu7EVPHhyooiVA4oaS2Z6yk="
  [mod."github.com/jonboulle/clockwork"]
    version = "v0.4.0"
    hash = "sha256-jj955cmaXwWpk7+ZTUxRds/lSt5ghkyyOesW/yFLM8g="
  [mod."github.com/klauspost/compress"]
    version = "v1.17.9"
    hash = "sha256-FxHk4OuwsbiH1OLI+Q0oA4KpcOB786sEfik0G+GNoow="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.2.8"
    hash = "sha256-/E58BnABQYxO+cmiue7OQqRLWkd/Lh8grX8DjTU4tk8="
  [mod."github.com/lib/pq"]
    version = "v1.10.4"
    hash = "sha256-gyHvt7ubYrrhwGKd3WWEkA15hlZ98NKDst4CkusDaCs="
  [mod."github.com/libdns/cloudflare"]
    version = "v0.1.2-0.20240604123710-0549667a10ab"
    hash = "sha256-7MTdbkr3vyo0sYorkISmLL618zeAJ5fltcv+7yQQ79I="
  [mod."github.com/libdns/libdns"]
    version = "v0.2.2"
    hash = "sha256-RaJz49yg14WVAxmmqvNfsL4PmQ16asg1rIipIKM3/QM="
  [mod."github.com/manifoldco/promptui"]
    version = "v0.9.0"
    hash = "sha256-Fe2OPoyRExZejwtUBivKhfJAJW7o9b1eyYpgDlWQ1No="
  [mod."github.com/mastercactapus/proxyprotocol"]
    version = "v0.0.4"
    hash = "sha256-7wUqy9EDfR9XM4FRQ5KoqiueGCujGRtGPHYMnI/2fW0="
  [mod."github.com/mattermost/xml-roundtrip-validator"]
    version = "v0.1.0"
    hash = "sha256-b5lspAL/mbHzYJmgHOSztGCDvqwhiVyk/c6DX9aWcQg="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mgutz/ansi"]
    version = "v0.0.0-20200706080929-d51e80ef957d"
    hash = "sha256-RY6deYqJKpTTttr5tH2VW+PtuUIcieEq3Y6fGqRL0vk="
  [mod."github.com/mholt/acmez/v2"]
    version = "v2.0.2"
    hash = "sha256-J5IZn0jnV2hAD3hSD/c3hFfNhg+JPNImsfb7vxPR34M="
  [mod."github.com/mholt/caddy-l4"]
    version = "v0.0.0-20240912211411-4f012d4517cf"
    hash = "sha256-M+FEiqV/uLIYv+FbXPTWME3OyT/jN5ZFtHQ+paBirWo="
  [mod."github.com/miekg/dns"]
    version = "v1.1.62"
    hash = "sha256-zEw71H0nX2C1fJykDcUHBthi9TT4a7vFidJ4RS5TunE="
  [mod."github.com/minio/md5-simd"]
    version = "v1.1.2"
    hash = "sha256-vykcXvy2VBBAXnJott/XsGTT0gk2UL36JzZKfJ1KAUY="
  [mod."github.com/minio/minio-go/v7"]
    version = "v7.0.75"
    hash = "sha256-Y8Z0X/D2JiaQT3bQBYzuOtQp8igEbU5BjfLy/Dw1w1c="
  [mod."github.com/mitchellh/copystructure"]
    version = "v1.2.0"
    hash = "sha256-VR9cPZvyW62IHXgmMw8ee+hBDThzd2vftgPksQYR/Mc="
  [mod."github.com/mitchellh/go-ps"]
    version = "v1.0.0"
    hash = "sha256-HzxVHNLHZpnsBuPcub0G+9jjDcDOsxM/6wifbsxf7EY="
  [mod."github.com/mitchellh/reflectwalk"]
    version = "v1.0.2"
    hash = "sha256-VX9DPqChm7jPnyrA3RAYgxAFrAhj7TRKIWD/qR9Zr9s="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/onsi/ginkgo/v2"]
    version = "v2.20.2"
    hash = "sha256-cWSrkASwco0tpynwHGiLvS4nZQCjk+eIvX/B9ohURqI="
  [mod."github.com/pires/go-proxyproto"]
    version = "v0.7.0"
    hash = "sha256-BIpJJu2ZIPrNURelm5VEejORQPMBHoCoOyjcXkrhKNw="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.20.3"
    hash = "sha256-cSgKoE7x6X0JuDT80Dtnve9jdxlTPzUGefy+fDuPd90="
  [mod."github.com/prometheus/client_model"]
    version = "v0.6.1"
    hash = "sha256-rIDyUzNfxRA934PIoySR0EhuBbZVRK/25Jlc/r8WODw="
  [mod."github.com/prometheus/common"]
    version = "v0.59.1"
    hash = "sha256-PYoEunC2Rx1KP8vH2inTD7uBCfUlvcROfeeAGRRjXPY="
  [mod."github.com/prometheus/procfs"]
    version = "v0.15.1"
    hash = "sha256-H+WXJemFFwdoglmD6p7JRjrJJZmIVAmJwYmLbZ8Q9sw="
  [mod."github.com/quic-go/qpack"]
    version = "v0.5.1"
    hash = "sha256-/r2LHWCfVD2vN3Vwso+El6fbQpy1xmQO4PwzHrfj2Lg="
  [mod."github.com/quic-go/quic-go"]
    version = "v0.47.0"
    hash = "sha256-X/noQoD18D0TT0hVtILI3ouwaa7/yMNVnvB93JIdL7o="
  [mod."github.com/rs/xid"]
    version = "v1.6.0"
    hash = "sha256-rJB7h3KuH1DPp5n4dY3MiGnV1Y96A10lf5OUl+MLkzU="
  [mod."github.com/russellhaering/goxmldsig"]
    version = "v1.4.0"
    hash = "sha256-5q2XyLETqpJM8kTOweyicDdw4CEQLYaJXcNR8ouCEic="
  [mod."github.com/russross/blackfriday/v2"]
    version = "v2.1.0"
    hash = "sha256-R+84l1si8az5yDqd5CYcFrTyNZ1eSYlpXKq6nFt4OTQ="
  [mod."github.com/shopspring/decimal"]
    version = "v1.4.0"
    hash = "sha256-U36bC271jQsjuWFF8BfLz4WicxPJUcPHRGxLvTz4Mdw="
  [mod."github.com/shurcooL/sanitized_anchor_name"]
    version = "v1.0.0"
    hash = "sha256-DtFSzeLmD1fAl103ncgwab7Vv2F0aulsA+gbkq24ab8="
  [mod."github.com/skip2/go-qrcode"]
    version = "v0.0.0-20200617195104-da1b6568686e"
    hash = "sha256-ST9t4/b7WFXUb8wra4ZYVDNZJGrEykw8dkWhLrxp8F0="
  [mod."github.com/slackhq/nebula"]
    version = "v1.9.4"
    hash = "sha256-i0fxZBvWpOqzSx7C4LTCGWhr9AmdA+8qjx0zzvoP7uU="
  [mod."github.com/smallstep/certificates"]
    version = "v0.27.4"
    hash = "sha256-zErUltk5+H5nhm4zUQbYiqY/a8DRXL6LThX79N8Rhf8="
  [mod."github.com/smallstep/nosql"]
    version = "v0.7.0"
    hash = "sha256-G3uQJCLiwHkIm9CIMxRXzHibihc1NXYLyZbYbeal/No="
  [mod."github.com/smallstep/pkcs7"]
    version = "v0.0.0-20240911091500-b1cae6277023"
    hash = "sha256-xTxzq0N2W6nYhEOJEUBV84ctfOY6Fti1N9NG9FhFmMo="
  [mod."github.com/smallstep/scep"]
    version = "v0.0.0-20240214080410-892e41795b99"
    hash = "sha256-26qHV4ACaSWiandGxfRfrOc5iTTcqqpKF7c4czXkaP4="
  [mod."github.com/smallstep/truststore"]
    version = "v0.13.0"
    hash = "sha256-Hs8FALZepOnVbUpOg99zdlhMMKAoPDp/i9ADM97jlio="
  [mod."github.com/spf13/cast"]
    version = "v1.7.0"
    hash = "sha256-xO2kSmNmMHaJ1i3T0ou0pcaBCusuO6Ep3xtF1P7ZadA="
  [mod."github.com/spf13/cobra"]
    version = "v1.8.1"
    hash = "sha256-yDF6yAHycV1IZOrt3/hofR+QINe+B2yqkcIaVov3Ky8="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/stoewer/go-strcase"]
    version = "v1.3.0"
    hash = "sha256-X0ilcefeqVQ44B9WT6euCMcigs7oLFypOQaGI33kGr8="
  [mod."github.com/tailscale/tscert"]
    version = "v0.0.0-20240608151842-d3f834017e53"
    hash = "sha256-7vp5qtuwweJewicY4XQSDY8IpGxKOsCQqDOyjkJMt28="
  [mod."github.com/techknowlogick/certmagic-s3"]
    version = "v1.3.0"
    hash = "sha256-EftQR9m/Ox9OOIdPY9mbTR5h8SIrhFJFkU6tJ4nUENc="
  [mod."github.com/things-go/go-socks5"]
    version = "v0.0.5"
    hash = "sha256-LP1Pxv/2zbLpL5/5jZHM6tTc1ov4WjGYgVdX6IDd2IU="
  [mod."github.com/urfave/cli"]
    version = "v1.22.15"
    hash = "sha256-7w+TJdKTHNmGq+pAJtPVMA073ruunHErzdxebH0dsVU="
  [mod."github.com/yroc92/postgres-storage"]
    version = "v0.0.0-20230310195636-276797aefe40"
    hash = "sha256-Cc2PCldDWlj/szufAkcjXAG9dFCRY5a4JD+48ajaky8="
  [mod."github.com/zeebo/blake3"]
    version = "v0.2.4"
    hash = "sha256-Q8KSVhnSR1cwfTp4LkPdfI1UWWkDDHa9fslNsa3Qfo8="
  [mod."go.etcd.io/bbolt"]
    version = "v1.3.11"
    hash = "sha256-SVWYZtE9TBgAo8xJSmo9DtSwuNa056N3zGvPLDJgiA8="
  [mod."go.step.sm/cli-utils"]
    version = "v0.9.0"
    hash = "sha256-sa2i2/XOZFiX5U2q7sZBcP+e3oJdGjPjf34lUanCoT0="
  [mod."go.step.sm/crypto"]
    version = "v0.52.0"
    hash = "sha256-NhJndfpJWAedjkDm/Kc3g/PkscUMnkNFjvSJts7XqRk="
  [mod."go.step.sm/linkedca"]
    version = "v0.22.1"
    hash = "sha256-WLokPz/UoSbQpuY7Qyy2YINW0t76E3kQvLIHrxVDTro="
  [mod."go.uber.org/automaxprocs"]
    version = "v1.5.3"
    hash = "sha256-f5mreEwkQ/tJxG7+6J7Vnh8nLSTz0P9x5KcoM1vDc/M="
  [mod."go.uber.org/mock"]
    version = "v0.4.0"
    hash = "sha256-mJN2cPmAMTZQzOnTpJ8zi9QH2m3OAKI4IpnQW9QYS8s="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."go.uber.org/zap"]
    version = "v1.27.0"
    hash = "sha256-8655KDrulc4Das3VRduO9MjCn8ZYD5WkULjCvruaYsU="
  [mod."go.uber.org/zap/exp"]
    version = "v0.2.0"
    hash = "sha256-H7IklrL7xaJB4jg86z6UUW+0kg4fu/chIqN/it1r+qY="
  [mod."golang.org/x/crypto"]
    version = "v0.27.0"
    hash = "sha256-8HP4+gr4DbXI22GhdgZmCWr1ijtI9HNLsTcE0kltY9o="
  [mod."golang.org/x/crypto/x509roots/fallback"]
    version = "v0.0.0-20240910204333-9e92970a1eb4"
    hash = "sha256-7dw0vcZ7oiuqynxdNvVE3WRjo4V3BdLRG1GXMN1IbjI="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20240909161429-701f63a606c0"
    hash = "sha256-nB3zQGSyCNU9Z6QP0iYYBpUeu7HKBBXS1z9ba4DxjMQ="
  [mod."golang.org/x/mod"]
    version = "v0.21.0"
    hash = "sha256-IpbTIlo0LX/WxyCrmVbAK/WzVPsmmrq2g/0JuJUaW2A="
  [mod."golang.org/x/net"]
    version = "v0.29.0"
    hash = "sha256-dH9Rdf5T04KJ4B5WvIZh12ogMbADWiWgIt77nvPTk2k="
  [mod."golang.org/x/oauth2"]
    version = "v0.23.0"
    hash = "sha256-K1X4ROG88PprttNjZCikDlZw8YYiQIQRdtbZBH3GJgM="
  [mod."golang.org/x/sync"]
    version = "v0.8.0"
    hash = "sha256-usvF0z7gq1vsX58p4orX+8WHlv52pdXgaueXlwj2Wss="
  [mod."golang.org/x/sys"]
    version = "v0.25.0"
    hash = "sha256-PXZ9EQZ7SFpcL7d3E1+KGTxziYlHEIZPfoXEbnaVD3I="
  [mod."golang.org/x/term"]
    version = "v0.24.0"
    hash = "sha256-PfC5psjzEWKRm1DlnBXX0ntw9OskJFrq1RRjyBa1lOk="
  [mod."golang.org/x/text"]
    version = "v0.18.0"
    hash = "sha256-aNvJW4gQs+MTfdz6DZqyyHQS2GJ9W8L8qKPVODPn4+k="
  [mod."golang.org/x/time"]
    version = "v0.6.0"
    hash = "sha256-gW9TVK9HjLk52lzfo5rBzSunc01gS0+SG2nk0X1w55M="
  [mod."golang.org/x/tools"]
    version = "v0.25.0"
    hash = "sha256-mAvdxYiufOJHTlXFGq0c16IgRgYYRVAqujPPWm+pL1M="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20240903143218-8af14fe29dc1"
    hash = "sha256-H40uIAZY8JMCAAe8+fLHbHMI/wNMUL8ukhBdS87p/2E="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20240903143218-8af14fe29dc1"
    hash = "sha256-4T4DTrmFbqT4tD7PSL7Ie7u8ZN2iwGkhK02nWugssxk="
  [mod."google.golang.org/grpc"]
    version = "v1.66.2"
    hash = "sha256-ZGEQK9lLC55Jkdifef/SO9mRPwEZmMJPXLH6MAKIGDA="
  [mod."google.golang.org/protobuf"]
    version = "v1.34.2"
    hash = "sha256-nMTlrDEE2dbpWz50eQMPBQXCyQh4IdjrTIccaU0F3m0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."howett.net/plist"]
    version = "v1.0.1"
    hash = "sha256-aXTwU+4m3JBjdX81Tw6MM8u4d39aoUICwP0g2ersmb0="
